---
version: latest
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/crdaley/komga/config
        target: /config
      - type: bind
        source: /mnt/data/komga/data
        target: /data
      - type: bind
        source: /etc/timezone #alternatively you can use a TZ environment variable, like TZ=Europe/London
        target: /etc/timezone
        read_only: true
    networks:
      - caddy
    labels:
      caddy: |
        lucisys.duckdns.org:25600
        192.168.1.13:25600
      caddy.reverse_proxy: "{{upstreams 25600}}"
      caddy.tls.lucisys.duckdns.org: letsencrypt
      caddy.tls.192.168.1.13: internal
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    restart: unless-stopped

networks:
  caddy:
    external: true
