---
version: latest
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /mnt/data/komga/config
        target: /config
      - type: bind
        source: /mnt/data/komga/data
        target: /data
      - type: bind
        read_only: true
    ports:
      - 25600:25600
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    environment:
      - <ENV_VAR>=<extra configuration>
      - TZ=America/New_York
      --mount type=bind,source=/mnt/data/komga/data,target=/data
    restart: unless-stopped
